(deftheme mytheme
  "Created 2019-11-19.")

(custom-theme-set-faces
 'mytheme
 '(cursor ((t (:background "#619ae7"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#4dd0e1"))))
 '(highlight ((t (:background "#a5c1e5" :inverse-video nil))))
 '(region ((t (:background "#a5c1e5"))))
 '(shadow ((t (:foreground "#b0bec5"))))
 '(secondary-selection ((t (:background "#bf616a"))))
 '(trailing-whitespace ((t (:underline nil :inverse-video t :foreground "#f36c60"))))
 '(font-lock-builtin-face ((t (:foreground "#fd9d9d"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#b0bec5"))))
 '(font-lock-comment-face ((t (:foreground "#b0bec5"))))
 '(font-lock-constant-face ((t (:foreground "#fd9d9d"))))
 '(font-lock-doc-face ((t (:foreground "#afb1b4"))))
 '(font-lock-function-name-face ((t (:foreground "#abbeff"))))
 '(font-lock-keyword-face ((t (:foreground "#afb1b4"))))
 '(font-lock-negation-char-face ((t (:foreground "#4dd0e1"))))
 '(font-lock-preprocessor-face ((t (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#fff59d"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#b39ddb"))))
 '(font-lock-string-face ((t (:foreground "#bef4b9"))))
 '(font-lock-type-face ((t (:foreground "#abbeff"))))
 '(font-lock-variable-name-face ((t (:foreground "#abbeff"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#f36c60"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line)))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:background "#263238"))))
 '(header-line ((t (:foreground "#b39ddb" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#ffffff" :background "#1c1f26"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#ffffff"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#ffffff"))))
 '(mode-line-highlight ((t (:box nil :foreground "#b39ddb"))))
 '(mode-line-inactive ((t (:weight normal :box nil :foreground "#a7adba" :background "#1c1f26" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#ffffff" :background "#8bc34a"))))
 '(isearch-fail ((t (:inverse-video t :background "#263238" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((t (:inverse-video nil :foreground "#263238" :background "#8bc34a"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :stipple nil :background "#202124" :foreground "#ffffff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "nil" :family "Menlo"))))
 '(font-latex-sectioning-5-face ((t (:inherit variable-pitch :foreground "#abbeff" :weight bold))))
 '(font-latex-italic-face ((t (:inherit italic :foreground "white"))))
 '(font-latex-bold-face ((t (:inherit bold :foreground "white"))))
 '(font-latex-math-face ((t (:foreground "#bef4b9"))))
 '(font-latex-warning-face ((t (:inherit bold :foreground "#fd9d9d"))))
 '(font-latex-string-face ((t (:foreground "#bef4b9"))))
 '(org-level-2 ((t (:inherit (outline-2)))))
 '(outline-2 ((t (:inherit font-lock-builtin-face))))
 '(org-level-1 ((t (:inherit (outline-1))))))

(provide-theme 'mytheme)
